name: pandabricks
display_name: "Panda Bricks"
description: "A modern take on the classic falling blocks game, featuring a playful panda theme and unique gameplay mechanics."
publish_to: 'none'
repository: https://github.com/teamsuperpanda/pandabricks
issue_tracker: https://github.com/teamsuperpanda/pandabricks/issues

version: 2.1.0+16

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter        
  intl: ^0.20.2       
  cupertino_icons: ^1.0.2
  audioplayers: ^6.5.1
  shimmer: ^3.0.0
  provider: ^6.1.5
  shared_preferences: ^2.5.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  mockito: ^5.6.1
  build_runner: ^2.11.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/launchscreen/
    - assets/audio/music/
    - assets/audio/music/game/
    - assets/audio/sfx/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ADD8E6"
  adaptive_icon_foreground: "assets/images/icon.png"
  # dart run flutter_launcher_icons

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1A1A1A"
  image: assets/images/launchscreen/logo_light.png
  image_dark: assets/images/launchscreen/logo_dark.png
  branding: assets/images/launchscreen/branding_light.png
  branding_dark: assets/images/launchscreen/branding_dark.png

  android_12:
    image: assets/images/launchscreen/logo_light.png
    image_dark: assets/images/launchscreen/logo_dark.png
    branding: assets/images/launchscreen/branding_light.png
    branding_dark: assets/images/launchscreen/branding_dark.png
    color: "#FFFFFF"
    color_dark: "#1A1A1A"
  android: true
  ios: false
  # dart run flutter_native_splash:create