name: pandabricks
display_name: "Panda Bricks"
description: "A modern take on the classic falling blocks game, featuring a playful panda theme and unique gameplay mechanics."
publish_to: 'none'

version: 2.0.0+9

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  audioplayers: ^5.2.1
  shimmer: ^3.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/
    # Audio
    - assets/audio/music/
    - assets/audio/music/game/
    - assets/audio/sfx/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ADD8E6"
  adaptive_icon_foreground: "assets/images/icon.png"
  # flutter launcher icons terminal command: flutter pub run flutter_launcher_icons

flutter_native_splash:
  android_12: 
    image: assets/images/logo.png
    branding: assets/images/branding.png
  color: "#1A1A1A"
  android: true
  # flutter native splash terminal command: dart run flutter_native_splash:create