name: pandabricks
display_name: "Panda Bricks"
description: "A modern take on the classic falling blocks game, featuring a playful panda theme and unique gameplay mechanics."
publish_to: 'none'

version: 2.0.0+9

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ADD8E6"
  adaptive_icon_foreground: "assets/images/icon.png"
  # flutter launcher icons terminal command: flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  android_12: 
    image: assets/images/logo.png
    branding: assets/images/branding.png
  color: "#1A1A1A"
  android: true
  # flutter native splash terminal command: flutter pub run flutter_native_splash:create